[package]
name = "cita-cli"
version = "0.17.0"
authors = ["piaoliu <441594700@qq.com>", "Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
dotenv = "^0.11.0"
clap = "^2.31.2"
ansi_term = "^0.10.0"
colored = "^1.6.0"
atty = "^0.2.10"
syntect = "^2.0.1"
serde = "^1.0.66"
serde_json = "^1.0.17"
lazy_static = "^1.0"
shell-words = "^0.1.0"
linefeed = "^0.5.0"
cita-tool = { path = "../cita-tool" }

[features]
default = []
blake2b_hash = ["cita-tool/blake2b_hash"]
